comments:
    path:     /
    defaults: { _controller: "BackEndBundle:Comentarios:index" }

comments_show:
    path:     /{id}/show
    defaults: { _controller: "BackEndBundle:Comentarios:show" }

comments_new:
    path:     /new
    defaults: { _controller: "BackEndBundle:Comentarios:new" }

comments_create:
    path:     /create
    defaults: { _controller: "BackEndBundle:Comentarios:create" }
    methods:  POST

comments_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackEndBundle:Comentarios:edit" }

comments_update:
    path:     /{id}/update
    defaults: { _controller: "BackEndBundle:Comentarios:update" }
    methods:  [POST, PUT]

comments_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackEndBundle:Comentarios:delete" }
    methods:  [POST, DELETE]
