marca:
    path:     /
    defaults: { _controller: "BackEndBundle:Marca:index" }

marca_show:
    path:     /{id}/show
    defaults: { _controller: "BackEndBundle:Marca:show" }

marca_new:
    path:     /new
    defaults: { _controller: "BackEndBundle:Marca:new" }

marca_create:
    path:     /create
    defaults: { _controller: "BackEndBundle:Marca:create" }
    methods:  POST

marca_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackEndBundle:Marca:edit" }

marca_update:
    path:     /{id}/update
    defaults: { _controller: "BackEndBundle:Marca:update" }
    methods:  [POST, PUT]

marca_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackEndBundle:Marca:delete" }
    methods:  [POST, DELETE]
