<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20160329031657 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql("INSERT INTO `role` ( `id` , `name` , `description` )VALUES ( 1, 'ROLE_SUPER_ADMINISTRATOR', '' ) ON DUPLICATE KEY UPDATE id=VALUES(id), name = VALUES (name)");
        $this->addSql("INSERT INTO `role` ( `id` , `name` , `description` )VALUES ( 2, 'ROLE_ADMINISTRATOR', '' ) ON DUPLICATE KEY UPDATE id=VALUES(id), name = VALUES (name)");
        $this->addSql("INSERT INTO `role` ( `id` , `name` , `description` )VALUES ( 3, 'ROLE_USER', '' ) ON DUPLICATE KEY UPDATE id=VALUES(id), name = VALUES (name)");

        $this->addSql("INSERT INTO `user` (`id`, `username`, `username_canonical`, `email`, `email_canonical`, `enabled`, `salt`, `password`, `last_login`, `locked`, `expired`, `expires_at`, `confirmation_token`, `password_requested_at`, `roles`, `credentials_expired`, `credentials_expire_at`, `name`, `lastname`)
                    VALUES (1, 'superadmin@gmail.com', 'superadmin@gmail.com', 'superadmin@gmail.com', 'superadmin@gmail.com', 1, 'b76tbyqp6q044cgs08wgsoc4ok0wcoo', 'zOhasWah/6N5g2ULM7/fLLGyAEH5zz6P1tqey4r6fXqbcNXltqWlg51jhrTC2bJiLRIdV4RGfjMoA8VeMzPNBQ==', '2015-11-07 15:49:17', 0, 0, NULL, NULL, NULL, 'a:0:{}', 0, NULL, 'Super-Admin', 'ADMIN')
                      ON DUPLICATE KEY UPDATE
                      id=VALUES(id),
                      username = VALUES (username),
                      username_canonical = VALUES (username_canonical),
                      email = VALUES (email),
                      email_canonical = VALUES (email_canonical),
                      enabled = VALUES (enabled),
                      salt = VALUES (salt),
                      password = VALUES (password),
                      last_login = VALUES (last_login),
                      locked = VALUES (locked),
                      expired = VALUES (expired),
                      expires_at = VALUES (expires_at),
                      confirmation_token = VALUES (confirmation_token),
                      password_requested_at = VALUES (password_requested_at),
                      roles = VALUES (roles),
                      credentials_expired = VALUES (credentials_expired),
                      name = VALUES (name),
                      lastname = VALUES (lastname)");

        $this->addSql("INSERT INTO `user_role` (`user_id` ,`role_id`)VALUES ('1', '1')");

        $this->addSql("INSERT INTO `country` (`id`,`code`,`name`) VALUES
                        (7, 'AF', 'Afghanistan'),
                        (8, 'AL', 'Albania'),
                        (9, 'DZ', 'Algeria'),
                        (10, 'AS', 'American Samoa'),
                        (11, 'AO', 'Angola'),
                        (12, 'AI', 'Anguilla'),
                        (13, 'AQ', 'Antartica'),
                        (14, 'an', 'Antigua and Barbuda'),
                        (15, 'AR', 'Argentina'),
                        (16, 'AM', 'Armenia'),
                        (17, 'AW', 'Aruba'),
                        (18, 'ash', 'Ashmore and Cartier Island'),
                        (19, 'AU', 'Australia'),
                        (20, 'AT', 'Austria'),
                        (21, 'AZ', 'Azerbaijan'),
                        (22, 'BS', 'Bahamas'),
                        (23, 'BH', 'Bahrain'),
                        (24, 'BD', 'Bangladesh'),
                        (25, 'BB', 'Barbados'),
                        (26, 'BY', 'Belarus'),
                        (27, 'BE', 'Belgium'),
                        (28, 'BZ', 'Belize'),
                        (29, 'BJ', 'Benin'),
                        (30, 'BM', 'Bermuda'),
                        (31, 'BT', 'Bhutan'),
                        (32, 'BO', 'Bolivia'),
                        (33, 'BA', 'Bosnia and Herzegovina'),
                        (34, 'BW', 'Botswana'),
                        (35, 'BR', 'Brazil'),
                        (36, 'bri', 'British Virgin Islands'),
                        (37, 'BN', 'Brunei'),
                        (38, 'BG', 'Bulgaria'),
                        (39, 'BF', 'Burkina Faso'),
                        (40, 'bur', 'Burma'),
                        (41, 'BI', 'Burundi'),
                        (42, 'KH', 'Cambodia'),
                        (43, 'CM', 'Cameroon'),
                        (45, 'CV', 'Cape Verde'),
                        (46, 'KY', 'Cayman Islands'),
                        (47, 'CF', 'Central African Republic'),
                        (48, 'TD', 'Chad'),
                        (49, 'CL', 'Chile'),
                        (50, 'CN', 'China'),
                        (51, 'CX', 'Christmas Island'),
                        (52, 'Cli', 'Clipperton Island'),
                        (53, 'CC', 'Cocos (Keeling) Islands'),
                        (54, 'CO', 'Colombia'),
                        (55, 'KM', 'Comoros'),
                        (56, 'CG', 'Congo, Democratic Republic of the'),
                        (57, 'CD', 'Congo, Republic of the'),
                        (58, 'CK', 'Cook Islands'),
                        (59, 'CR', 'Costa Rica'),
                        (60, 'CI', 'Cote d''Ivoire'),
                        (61, 'HR', 'Croatia'),
                        (62, 'CU', 'Cuba'),
                        (63, 'CY', 'Cyprus'),
                        (64, 'CZ', 'Czeck Republic'),
                        (65, 'DK', 'Denmark'),
                        (66, 'DJ', 'Djibouti'),
                        (67, 'DM', 'Dominica'),
                        (68, 'DO', 'Dominican Republic'),
                        (69, 'EC', 'Ecuador'),
                        (70, 'EG', 'Egypt'),
                        (71, 'SV', 'El Salvador'),
                        (72, 'GQ', 'Equatorial Guinea'),
                        (73, 'ER', 'Eritrea'),
                        (74, 'EE', 'Estonia'),
                        (75, 'ET', 'Ethiopia'),
                        (76, 'Eur', 'Europa Island'),
                        (77, 'FK', 'Falkland Islands (Islas Malvinas)'),
                        (78, 'FO', 'Faroe Islands'),
                        (79, 'FJ', 'Fiji'),
                        (80, 'FI', 'Finland'),
                        (82, 'GF', 'French Guiana'),
                        (83, 'PF', 'French Polynesia'),
                        (84, 'TF', 'French Southern and Antarctic Lands'),
                        (85, 'GA', 'Gabon'),
                        (86, 'GM', 'Gambia, The'),
                        (87, 'Gaz', 'Gaza Strip'),
                        (88, 'GE', 'Georgia'),
                        (89, 'DE', 'Germany'),
                        (90, 'GH', 'Ghana'),
                        (91, 'GI', 'Gibraltar'),
                        (92, 'Glo', 'Glorioso Islands'),
                        (93, 'GR', 'Greece'),
                        (94, 'GL', 'Greenland'),
                        (95, 'GD', 'Grenada'),
                        (96, 'GP', 'Guadeloupe'),
                        (97, 'GU', 'Guam'),
                        (98, 'GT', 'Guatemala'),
                        (99, 'Gue', 'Guernsey'),
                        (100, 'GN', 'Guinea'),
                        (101, 'GW', 'Guinea-Bissau'),
                        (102, 'GY', 'Guyana'),
                        (103, 'HT', 'Haiti'),
                        (104, 'HM', 'Heard Island and McDonald Islands'),
                        (105, 'VA', 'Holy See (Vatican City)'),
                        (106, 'HN', 'Honduras'),
                        (107, 'HK', 'Hong Kong'),
                        (108, 'How', 'Howland Island'),
                        (109, 'HU', 'Hungary'),
                        (110, 'IS', 'Iceland'),
                        (111, 'IN', 'India'),
                        (112, 'ID', 'Indonesia'),
                        (113, 'IR', 'Iran'),
                        (114, 'IQ', 'Iraq'),
                        (115, 'IE', 'Ireland'),
                        (116, 'Ire', 'Ireland, Northern'),
                        (117, 'IL', 'Israel'),
                        (119, 'JM', 'Jamaica'),
                        (120, 'Jan', 'Jan Mayen'),
                        (121, 'JP', 'Japan'),
                        (122, 'Jar', 'Jarvis Island'),
                        (123, 'Jer', 'Jersey'),
                        (124, 'Joh', 'Johnston Atoll'),
                        (125, 'JO', 'Jordan'),
                        (126, 'Jua', 'Juan de Nova Island'),
                        (127, 'KZ', 'Kazakhstan'),
                        (128, 'KE', 'Kenya'),
                        (129, 'KI', 'Kiribati'),
                        (130, 'KP', 'Korea, North'),
                        (131, 'KR', 'Korea, South'),
                        (132, 'KW', 'Kuwait'),
                        (133, 'KG', 'Kyrgyzstan'),
                        (134, 'LA', 'Laos'),
                        (135, 'LV', 'Latvia'),
                        (136, 'LB', 'Lebanon'),
                        (137, 'LS', 'Lesotho'),
                        (138, 'LR', 'Liberia'),
                        (139, 'LY', 'Libya'),
                        (140, 'LI', 'Liechtenstein'),
                        (141, 'LT', 'Lithuania'),
                        (142, 'LU', 'Luxembourg'),
                        (143, 'MO', 'Macau'),
                        (144, 'MK', 'Macedonia, Former Yugoslav Republic of'),
                        (145, 'MG', 'Madagascar'),
                        (146, 'MW', 'Malawi'),
                        (147, 'MY', 'Malaysia'),
                        (148, 'MV', 'Maldives'),
                        (149, 'ML', 'Mali'),
                        (150, 'MT', 'Malta'),
                        (151, 'Man', 'Man, Isle of'),
                        (152, 'MH', 'Marshall Islands'),
                        (153, 'MQ', 'Martinique'),
                        (154, 'MR', 'Mauritania'),
                        (155, 'MU', 'Mauritius'),
                        (156, 'YT', 'Mayotte'),
                        (157, 'MX', 'Mexico'),
                        (158, 'FM', 'Micronesia, Federated States of'),
                        (159, 'Mid', 'Midway Islands'),
                        (160, 'MD', 'Moldova'),
                        (161, 'MC', 'Monaco'),
                        (162, 'MN', 'Mongolia'),
                        (163, 'MS', 'Montserrat'),
                        (164, 'MA', 'Morocco'),
                        (165, 'MZ', 'Mozambique'),
                        (166, 'NA', 'Namibia'),
                        (167, 'NR', 'Nauru'),
                        (168, 'NP', 'Nepal'),
                        (169, 'NL', 'Netherlands'),
                        (170, 'AN', 'Netherlands Antilles'),
                        (171, 'NC', 'New Caledonia'),
                        (172, 'NZ', 'New Zealand'),
                        (173, 'NI', 'Nicaragua'),
                        (174, 'NE', 'Niger'),
                        (175, 'NG', 'Nigeria'),
                        (176, 'NU', 'Niue'),
                        (177, 'NF', 'Norfolk Island'),
                        (178, 'MP', 'Northern Mariana Islands'),
                        (179, 'NO', 'Norway'),
                        (180, 'OM', 'Oman'),
                        (181, 'PK', 'Pakistan'),
                        (182, 'PW', 'Palau'),
                        (183, 'PA', 'Panama'),
                        (184, 'PG', 'Papua New Guinea'),
                        (185, 'PY', 'Paraguay'),
                        (186, 'PE', 'Peru'),
                        (187, 'PH', 'Philippines'),
                        (188, 'PN', 'Pitcaim Islands'),
                        (189, 'PL', 'Poland'),
                        (190, 'PT', 'Portugal'),
                        (191, 'PR', 'Puerto Rico'),
                        (192, 'QA', 'Qatar'),
                        (193, 'RE', 'Reunion'),
                        (194, 'RO', 'Romainia'),
                        (195, 'RU', 'Russia'),
                        (196, 'RW', 'Rwanda'),
                        (197, 'Sai', 'Saint Helena'),
                        (198, 'KN', 'Saint Kitts and Nevis'),
                        (199, 'LC', 'Saint Lucia'),
                        (200, 'Sai', 'Saint Pierre and Miquelon'),
                        (201, 'VC', 'Saint Vincent and the Grenadines'),
                        (202, 'WS', 'Samoa'),
                        (203, 'SM', 'San Marino'),
                        (204, 'ST', 'Sao Tome and Principe'),
                        (205, 'SA', 'Saudi Arabia'),
                        (206, 'Sco', 'Scotland'),
                        (207, 'SN', 'Senegal'),
                        (208, 'SC', 'Seychelles'),
                        (209, 'SL', 'Sierra Leone'),
                        (210, 'SG', 'Singapore'),
                        (211, 'SK', 'Slovakia'),
                        (212, 'SI', 'Slovenia'),
                        (213, 'SB', 'Solomon Islands'),
                        (214, 'SO', 'Somalia'),
                        (215, 'ZA', 'South Africa'),
                        (216, 'GS', 'South Georgia and South Sandwich Islands'),
                        (218, 'Spr', 'Spratly Islands'),
                        (219, 'LK', 'Sri Lanka'),
                        (220, 'SD', 'Sudan'),
                        (221, 'SR', 'Suriname'),
                        (222, 'SJ', 'Svalbard'),
                        (223, 'SZ', 'Swaziland'),
                        (224, 'SE', 'Sweden'),
                        (226, 'SY', 'Syria'),
                        (227, 'TW', 'Taiwan'),
                        (228, 'TJ', 'Tajikistan'),
                        (229, 'TZ', 'Tanzania'),
                        (230, 'TH', 'Thailand'),
                        (231, 'Tob', 'Tobago'),
                        (232, 'TG', 'Toga'),
                        (233, 'TK', 'Tokelau'),
                        (234, 'TO', 'Tonga'),
                        (235, 'TT', 'Trinidad and Tobago'),
                        (236, 'TN', 'Tunisia'),
                        (237, 'TR', 'Turkey'),
                        (238, 'TM', 'Turkmenistan'),
                        (239, 'TV', 'Tuvalu'),
                        (240, 'UG', 'Uganda'),
                        (241, 'UA', 'Ukraine'),
                        (242, 'AE', 'United Arab Emirates'),
                        (243, 'GB', 'United Kingdom'),
                        (244, 'UY', 'Uruguay'),
                        (245, 'US', 'United States'),
                        (246, 'UZ', 'Uzbekistan'),
                        (247, 'VU', 'Vanuatu'),
                        (248, 'VE', 'Venezuela'),
                        (249, 'VN', 'Vietnam'),
                        (250, 'VG', 'Virgin Islands'),
                        (251, 'Wal', 'Wales'),
                        (252, 'WF', 'Wallis and Futuna'),
                        (253, 'Wes', 'West Bank'),
                        (254, 'EH', 'Western Sahara'),
                        (255, 'YE', 'Yemen'),
                        (256, 'Yug', 'Yugoslavia'),
                        (257, 'ZM', 'Zambia'),
                        (258, 'ZW', 'Zimbabwe')");

        $this->addSql("INSERT INTO currency (id, code, name, exchange_rate, symbol,is_default,enabled ) VALUES (1, 'USD', 'Dollar', '1.1000', '$', 1, 0), (2, 'EUR', 'Euro', '1.6000', '€', 0, 0),(3, 'CHF', 'Swiss Franc', '1.0000', 'SFr', 0 , 0)");

        $this->addSql('INSERT INTO language VALUES (1, "ENG", "English", "en")');
        $this->addSql('INSERT INTO language VALUES (3, "ESP", "Español", "es")');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs

    }
}
