<?php

namespace BackEndBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * currencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends EntityRepository
{
    public function getDefaultCurrency(){
        $queryBuilder = $this->createQueryBuilder('p');
        $queryBuilder->where('p.default = 1');
        if(count($queryBuilder->getQuery()->getResult()))
            return $queryBuilder->getQuery()->getResult()[0]->getCode();

        return 'USD';
    }
}
