<?php

namespace BackEndBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HafacilidadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HafacilidadesRepository extends EntityRepository
{

}
