<?php

namespace BackEndBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MotivosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotivosRepository extends EntityRepository
{

}
