<?php

namespace BackEndBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RedesSocialesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedesSocialesRepository extends EntityRepository
{

}
