services:
#    front_end.example:
#        class: FrontEndBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

     hotel.locale_listener:
         class: FrontEndBundle\EventListener\LocaleListener
         arguments:
           - 'en'
           - @currency.repository
         tags:
           - { name: kernel.event_subscriber }
