back_end_servicios:
    resource: "@BackEndBundle/Resources/config/routing/servicios.yml"
    prefix:   /servicios

back_end_respuesta:
    resource: "@BackEndBundle/Resources/config/routing/respuesta.yml"
    prefix:   /respuesta

back_end_reserva:
    resource: "@BackEndBundle/Resources/config/routing/reserva.yml"
    prefix:   /reserva

back_end_redessociales:
    resource: "@BackEndBundle/Resources/config/routing/redessociales.yml"
    prefix:   /redessociales

back_end_motivos:
    resource: "@BackEndBundle/Resources/config/routing/motivos.yml"
    prefix:   /motivos

back_end_marca:
    resource: "@BackEndBundle/Resources/config/routing/marca.yml"
    prefix:   /marca

back_end_hotel:
    resource: "@BackEndBundle/Resources/config/routing/hotel.yml"
    prefix:   /hotel

back_end_hofacilidades:
    resource: "@BackEndBundle/Resources/config/routing/hofacilidades.yml"
    prefix:   /hofacilidades

back_end_hafacilidades:
    resource: "@BackEndBundle/Resources/config/routing/hafacilidades.yml"
    prefix:   /hafacilidades

back_end_habitacion:
    resource: "@BackEndBundle/Resources/config/routing/habitacion.yml"
    prefix:   /habitacion

back_end_gastronomy:
    resource: "@BackEndBundle/Resources/config/routing/gastronomia.yml"
    prefix:   /gastronomy

back_end_faq:
    resource: "@BackEndBundle/Resources/config/routing/faq.yml"
    prefix:   /faq

back_end_comments:
    resource: "@BackEndBundle/Resources/config/routing/comentarios.yml"
    prefix:   /comments

back_end_homepage:
    path:     /hello/{name}
    defaults: { _controller: BackEndBundle:Default:index }

backend_routes:
    resource: "@BackEndBundle/Controller/"
    type:     annotation

backend_login:
    pattern:  /login
    defaults: { _controller: FOSUserBundle:Security:login }

backend_login_check:
    pattern:  /login_check
    defaults: { _controller: FOSUserBundle:Security:check }

backend_logout:
    path: fos_user_security_logout
