services:
#    back_end.example:
#        class: BackEndBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

#Entities Repositories Services

#    comentarios
    comentarios.repository:
            alias: comentarios.repository.doctrine
            public: true

    comentarios.repository.doctrine:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ BackEndBundle\Entity\Comentarios ]
        public: false

#    gastronomia
    gastronomia.repository:
            alias: gastronomia.repository.doctrine
            public: true

    gastronomia.repository.doctrine:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ BackEndBundle\Entity\Gastronomia ]
        public: false

#    habitacion
    habitacion.repository:
            alias: habitacion.repository.doctrine
            public: true

    habitacion.repository.doctrine:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ BackEndBundle\Entity\Habitacion ]
        public: false


#    hotel
    hotel.repository:
            alias: hotel.repository.doctrine
            public: true

    hotel.repository.doctrine:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ BackEndBundle\Entity\Hotel ]
        public: false

#    marca
    marca.repository:
            alias: marca.repository.doctrine
            public: true

    marca.repository.doctrine:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ BackEndBundle\Entity\Marca ]
        public: false

#    motivos
    motivos.repository:
            alias: motivos.repository.doctrine
            public: true

    motivos.repository.doctrine:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ BackEndBundle\Entity\Motivos ]
        public: false

#    reserva
    reserva.repository:
            alias: reserva.repository.doctrine
            public: true

    reserva.repository.doctrine:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ BackEndBundle\Entity\Reserva ]
        public: false


#    servicios
    servicios.repository:
            alias: servicios.repository.doctrine
            public: true

    servicios.repository.doctrine:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ BackEndBundle\Entity\Servicios ]
        public: false


#    respuesta
    respuesta.repository:
            alias: respuesta.repository.doctrine
            public: true

    respuesta.repository.doctrine:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ BackEndBundle\Entity\Respuesta ]
        public: false

#    redes_sociales
    redes_sociales.repository:
            alias: redes_sociales.repository.doctrine
            public: true

    redes_sociales.repository.doctrine:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ BackEndBundle\Entity\RedesSociales ]
        public: false

#    hafacilidades
    hafacilidades.repository:
            alias: hafacilidades.repository.doctrine
            public: true

    hafacilidades.repository.doctrine:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ BackEndBundle\Entity\Hafacilidades ]
        public: false

#    hofacilidades
    hofacilidades.repository:
            alias: hofacilidades.repository.doctrine
            public: true

    hofacilidades.repository.doctrine:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ BackEndBundle\Entity\Hofacilidades ]
        public: false

#    faq
    faq.repository:
            alias: faq.repository.doctrine
            public: true

    faq.repository.doctrine:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ BackEndBundle\Entity\Faq ]
        public: false

#    languages
    language.repository:
        alias: lenguage.repository.doctrine
        public: true

    lenguage.repository.doctrine:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ BackEndBundle\Entity\Language ]
        public: false

#    languages
    currency.repository:
        alias: currency.repository.doctrine
        public: true

    currency.repository.doctrine:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ BackEndBundle\Entity\Currency ]
        public: false